"""Tests for glados.core.source_context."""

from __future__ import annotations

import pytest

from glados.core.source_context import SourceContext
from glados.observability.audit import Origin


class TestFromHeaders:
    def test_full_set_of_headers(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "webui_chat",
            "X-GLaDOS-Session-Id": "sess-abc",
            "X-GLaDOS-Area-Id": "living_room",
            "X-GLaDOS-Principal": "ResidentA",
            "X-GLaDOS-Satellite-Device-Id": "esphome_liv_sat",
        })
        assert ctx.origin == Origin.WEBUI_CHAT
        assert ctx.channel == "chat"
        assert ctx.session_id == "sess-abc"
        assert ctx.area_id == "living_room"
        assert ctx.principal == "ResidentA"
        assert ctx.satellite_device_id == "esphome_liv_sat"

    def test_case_insensitive_header_keys(self) -> None:
        # HTTP headers are case-insensitive; the context must match
        # regardless of the casing the client or proxy used.
        ctx = SourceContext.from_headers({
            "x-glados-origin": "api_chat",
            "X-GLADOS-SESSION-ID": "sess-1",
        })
        assert ctx.origin == Origin.API_CHAT
        assert ctx.session_id == "sess-1"

    def test_voice_mic_origin_derives_voice_channel(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "voice_mic",
            "X-GLaDOS-Session-Id": "sat-1",
            "X-GLaDOS-Area-Id": "office",
        })
        assert ctx.channel == "voice"
        assert ctx.area_id == "office"

    def test_unknown_origin_normalized(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "totally_made_up",
            "X-GLaDOS-Session-Id": "x",
        })
        assert ctx.origin == Origin.UNKNOWN
        assert ctx.channel == "chat"  # safer default

    def test_missing_origin_uses_default(self) -> None:
        ctx = SourceContext.from_headers(
            {"X-GLaDOS-Session-Id": "x"},
            default_origin=Origin.AUTONOMY,
        )
        assert ctx.origin == Origin.AUTONOMY

    def test_missing_session_id_generates_one(self) -> None:
        ctx = SourceContext.from_headers({"X-GLaDOS-Origin": "api_chat"})
        # Autogenerated UUID4 hex is 32 chars
        assert len(ctx.session_id) == 32
        assert all(c in "0123456789abcdef" for c in ctx.session_id)

    def test_empty_area_is_none(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "webui_chat",
            "X-GLaDOS-Session-Id": "x",
            "X-GLaDOS-Area-Id": "   ",
        })
        assert ctx.area_id is None


class TestFromExtraBody:
    def test_full_body(self) -> None:
        ctx = SourceContext.from_extra_body({
            "origin": "webui_chat",
            "session_id": "sess-2",
            "area_id": "bedroom",
            "principal": "ResidentA",
            "satellite_device_id": "dev-1",
        })
        assert ctx.origin == Origin.WEBUI_CHAT
        assert ctx.area_id == "bedroom"
        assert ctx.satellite_device_id == "dev-1"

    def test_none_body(self) -> None:
        ctx = SourceContext.from_extra_body(None)
        assert ctx.origin == Origin.UNKNOWN
        assert ctx.session_id  # autogenerated

    def test_empty_strings_become_none(self) -> None:
        ctx = SourceContext.from_extra_body({
            "origin": "webui_chat",
            "session_id": "s",
            "area_id": "",
            "principal": "   ",
        })
        assert ctx.area_id is None
        assert ctx.principal is None


class TestImmutabilityAndHelpers:
    def test_frozen_dataclass(self) -> None:
        ctx = SourceContext.from_headers({"X-GLaDOS-Origin": "webui_chat"})
        with pytest.raises((AttributeError, TypeError)):
            ctx.origin = "api_chat"  # type: ignore[misc]

    def test_with_area_returns_new_instance(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "voice_mic",
            "X-GLaDOS-Session-Id": "sat-1",
            "X-GLaDOS-Satellite-Device-Id": "esp-1",
        })
        assert ctx.area_id is None
        updated = ctx.with_area("office")
        assert updated.area_id == "office"
        assert ctx.area_id is None  # original unchanged
        # Everything else copied verbatim
        assert updated.origin == ctx.origin
        assert updated.session_id == ctx.session_id
        assert updated.satellite_device_id == ctx.satellite_device_id
        assert updated.timestamp == ctx.timestamp

    def test_to_audit_fields_elides_empty(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "webui_chat",
            "X-GLaDOS-Session-Id": "s",
        })
        fields = ctx.to_audit_fields()
        assert fields == {"channel": "chat", "session_id": "s"}

    def test_to_audit_fields_includes_area_and_device(self) -> None:
        ctx = SourceContext.from_headers({
            "X-GLaDOS-Origin": "voice_mic",
            "X-GLaDOS-Session-Id": "s",
            "X-GLaDOS-Area-Id": "kitchen",
            "X-GLaDOS-Satellite-Device-Id": "sat-k",
        })
        fields = ctx.to_audit_fields()
        assert fields["area_id"] == "kitchen"
        assert fields["satellite_device_id"] == "sat-k"
        assert fields["channel"] == "voice"


class TestTimestampOverride:
    def test_explicit_timestamp(self) -> None:
        ctx = SourceContext(
            origin=Origin.WEBUI_CHAT,
            channel="chat",
            session_id="s",
            timestamp=1234.5,
        )
        assert ctx.timestamp == 1234.5
