"""Generate baresip config + accounts files from a ``SipConfig``.

baresip reads two text files at startup (in the directory passed via
``-f <dir>``):

- ``config``: one ``key value`` per line; modules listed as ``module name.so``
- ``accounts``: one SIP AOR per line with ``;auth_pass=...`` parameters

This module renders both from a typed ``SipConfig`` so they're consistent
with whatever ``configs/sip.yaml`` says.

We deliberately keep the module list minimal (only what Slice 1 needs)
to reduce surface area and skip baresip's GUI/X11 modules that pull in
GPL/LGPL deps we excluded at the apt layer.
"""
from __future__ import annotations

import pathlib

from glados.sip.config import SipConfig


# baresip modules required for Slice 1 inbound:
#   account.so  — load /tmp/baresip/accounts
#   ctrl_tcp.so — JSON control interface on loopback (Task 4)
#   aufile.so   — read/write PCM audio from named pipes (Task 5)
#   g711.so     — μ-law (PCMU) + A-law (PCMA) codecs
#   g722.so     — 16 kHz wideband codec (preferred when PBX supports it)
#   telev.so    — RFC 2833 telephone-event (DTMF over RTP)
#   dtmf.so     — DTMF event dispatch into ctrl_tcp
#   stun.so     — STUN client for NAT awareness on the LAN
_REQUIRED_MODULES = (
    "account.so",
    "ctrl_tcp.so",
    "aufile.so",
    "g711.so",
    "g722.so",
    "telev.so",
    "dtmf.so",
    "stun.so",
)


def render_config(cfg: SipConfig, *, ctrl_tcp_port: int = 4444,
                  rx_fifo: str = "/tmp/sip-rx.fifo",
                  tx_fifo: str = "/tmp/sip-tx.fifo") -> str:
    """Return the body of baresip's ``config`` file.

    Args:
        cfg: parsed SIP config.
        ctrl_tcp_port: loopback port baresip's ctrl_tcp module listens on.
        rx_fifo: named pipe baresip writes incoming-audio PCM into.
        tx_fifo: named pipe baresip reads outgoing-audio PCM from.
    """
    codec_pref = ",".join(cfg.audio.codec_preference)
    lines: list[str] = [
        "# Auto-generated by glados.sip._baresip_config — do NOT hand-edit.",
        "# Source of truth: configs/sip.yaml. Restart the container to apply changes.",
        "",
        "# ── Modules ──────────────────────────────────────────────────",
    ]
    lines.extend(f"module {m}" for m in _REQUIRED_MODULES)
    lines.extend([
        "",
        "# ── Audio (PCM via named pipes) ──────────────────────────────",
        f"audio_player aufile,{tx_fifo}",
        f"audio_source aufile,{rx_fifo}",
        "audio_srate 8000",
        "audio_channels 1",
        "",
        "# ── SIP ──────────────────────────────────────────────────────",
        f"sip_listen 0.0.0.0:{cfg.server.port}",
        "sip_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem",
        "",
        "# ── RTP ──────────────────────────────────────────────────────",
        f"rtp_ports {cfg.audio.rtp_port_low}-{cfg.audio.rtp_port_high}",
        "rtp_timeout 60",
        "",
        "# ── Codec preferences ────────────────────────────────────────",
        f"audio_codecs {codec_pref}",
        "",
        "# ── Control interface ────────────────────────────────────────",
        f"ctrl_tcp_listen 127.0.0.1:{ctrl_tcp_port}",
        "",
        "# ── Misc ─────────────────────────────────────────────────────",
        "log_level 3",  # 3 = INFO; bump to 4 for DEBUG when troubleshooting
    ])
    return "\n".join(lines) + "\n"


def render_accounts(cfg: SipConfig) -> str:
    """Return the body of baresip's ``accounts`` file.

    One AOR line — Slice 1 has a single SIP account (the GLaDOS
    extension on the operator's PBX).
    """
    s = cfg.server
    parts = [
        f"<sip:{s.username}@{s.host}>",
        f";auth_pass={s.password}" if s.password else "",
        f";regint={s.register_expires}",
        f";transport={s.transport.lower()}",
    ]
    if s.realm:
        parts.append(f";auth_user={s.username}")  # auth_user often differs from URI user; we set both equal here
    return "".join(parts) + "\n"


def write_baresip_files(cfg: SipConfig, outdir: pathlib.Path | str, **kwargs) -> None:
    """Render config + accounts to ``outdir``. Creates the directory if missing.

    Extra kwargs are forwarded to ``render_config`` (ctrl_tcp_port,
    rx_fifo, tx_fifo).
    """
    outdir = pathlib.Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "config").write_text(render_config(cfg, **kwargs), encoding="utf-8")
    (outdir / "accounts").write_text(render_accounts(cfg), encoding="utf-8")
